random_seed: 123

num_workers: 8

wandb:
  project: opf-dataset-utils
  offline: False

defaults:
  - data: default
  - training: default
  - _self_ # https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order/