bus_retention_ratio: 1.0

bus_size_range:
  min: 20
  max: 40

edit_distance:
  approximation_iterations: 1
  num_bins: 20
  num_samples: 100
  subgraphs: True

equipment_retention_ratio: 1.0

filepath: data/case118_120000.json
#filepath: data/dataset_release_1/pglib_opf_case14_ieee/raw/gridopt-dataset-tmp/dataset_release_1/pglib_opf_case14_ieee/group_0/example_0.json

inches_per:
  row: 3
  column: 3

node_size: 50

num_columns: 5

num_hops_range:
  min: 3
  max: 7

num_subgraphs: 10

random_seed: 1

saving:
  filepath: img/sampled_subgraph.pdf

show: True

